/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutToast: typeof import('@nutui/nutui-taro')['Toast']
  }
}
